development:
  adapter: jdbcmysql
  database: git_development
  username: root
  password:
  host: localhost

test:
  adapter: jdbcmysql
  database: git_test
  username: root
  password:
  host: localhost
